inverters:
- enabled: true
  firmware_version: ''
  host: 192.168.3.18
  id: bf0b8e3aaaef
  manufacturer: ''
  model: ''
  port: 1502
  serial: ''
  unit_id: 1
log_level: DEBUG
night_mode:
  threshold_seconds: 300.0
proxy:
  host: 0.0.0.0
  poll_interval: 1.0
  port: 5020
  staleness_timeout: 30.0
venus:
  host: ''
  port: 1883
  portal_id: ''
webapp:
  port: 8080
